= MongoDB Service Broker for Pivotal Cloud Foundry

== Getting Started

. Install and run MongoDB somewhere accessable by Cloud Foundry

. Checkout the MongoDB service broker (this repo) from github
* *Option 1:* Upload the .pivotal artifact in mongodb-broker/tile/product/releases to your Ops Manager (tested on and works on Version 1.6.9+) and set up your MongoDB configuration
* *Option 2:* Build yourself: requires link:http://cf-platform-eng.github.io/isv-portal/tile-generator/[Tile Generator] installed
+
----
$ cd mongodb-broker
$ mvn clean
$ mvn package
$ cd tile
$ tile init
$ tile build
----
+
Upload the newly created .pivotal artifact from mongodb-broker/tile/product/releases to your Ops Manager (tested on and works on Version 1.6.9+) and set up your MongoDB configuration as usual

. Create security group needed by the tile config (you can override this if you wish by flipping the flag in tile.yml)
+
----
$ touch all_open.json
----
+
. Copy below template into *all_open.json* 
+
----
[
    {
       	"destination": "0.0.0.0-255.255.255.255",
        "protocol": "all"
    }
]
----
+
. In same directory, use CF Cli to make add new security group to deployment
+
----
$ cf create-security-group all_open all_open.json
----
. Configure and deploy the tile
